#!/usr/bin/env python3
"""Apply all streaming links to albums.json."""

import json
import os

albums_path = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'albums.json')
with open(albums_path) as f:
    albums = json.load(f)

# Apple Music links from iTunes Search API
apple_music_path = '/tmp/apple_music_links.json'
apple_music = {}
if os.path.exists(apple_music_path):
    with open(apple_music_path) as f:
        apple_music = json.load(f)

# Spotify links from search agents (5 batches)
spotify = {
    # Batch 1
    "hot-fives-sevens": "https://open.spotify.com/album/62tjAbmtJSVxuSJ0jQc1GW",
    "ellington-at-newport": "https://open.spotify.com/album/0tHfUPQwdystxD41YUZ9cm",
    "kind-of-blue": "https://open.spotify.com/album/1weenld61qoidwYuZ1GESA",
    "a-love-supreme": "https://open.spotify.com/album/7Eoz7hJvaX1eFkbpQxC5PA",
    "blue-train": "https://open.spotify.com/album/2Z11cXWEa2qqYQBGkJrCga",
    "moanin": "https://open.spotify.com/album/2D4kqfmUPMNlVSGpYmNx5X",
    "brilliant-corners": "https://open.spotify.com/album/5gWF47eGSbv4BOfxoFcQtd",
    "the-shape-of-jazz-to-come": "https://open.spotify.com/album/2iPH3iUmpa9ufIpwY76keF",
    "head-hunters": "https://open.spotify.com/album/5fmIolILp5NAtNYiRPjhzA",
    "maiden-voyage": "https://open.spotify.com/album/4PMwCdbTTBTgyMh8dbTVRb",
    "time-out": "https://open.spotify.com/album/0nTTEAhCZsbbeplyDMIFuA",
    "bitches-brew": "https://open.spotify.com/album/3Q0zkOZEOC855ErOOJ1AdO",
    "birth-of-the-cool": "https://open.spotify.com/album/0QWea2w5Y6pSoSWHuc7JMf",
    "mingus-ah-um": "https://open.spotify.com/album/7pojWP7x9uEFSJgw765khA",
    "saxophone-colossus": "https://open.spotify.com/album/2dtjLAwt7Cq763h6AupyPZ",
    "the-black-saint": "https://open.spotify.com/album/6Sts4Yh7KsDFwq2yTWrGGV",
    "speak-no-evil": "https://open.spotify.com/album/4XFdCNG4qolHR4nm5vhwBd",
    "out-to-lunch": "https://open.spotify.com/album/2iaiI4nHOV0c3YxUVqv2eN",
    "sunday-at-the-village-vanguard": "https://open.spotify.com/album/68e5Cxo3UmbgYbE2tWm8Ov",
    "giant-steps": "https://open.spotify.com/album/7cZ6oBx0SEUPDAoxJtxNDh",
    "money-jungle": "https://open.spotify.com/album/5I3aoewqDpP4TglIl9O7su",
    "the-sidewinder": "https://open.spotify.com/album/3d6tzNMyeFLz0TEh5pdYOr",
    "song-for-my-father": "https://open.spotify.com/album/4LEnATSqKeANOJ0mLUAuCE",
    "at-carnegie-hall": "https://open.spotify.com/album/3x38mYlwkm6L6vYIn0Hzqk",
    "free-jazz": "https://open.spotify.com/album/4tg1cOSMLzEeTfLOuHM1WX",
    "chet-baker-sings": "https://open.spotify.com/album/5JJ779nrbHx0KB2lBrMMa4",
    "getz-gilberto": "https://open.spotify.com/album/73ZRKdD3Ds43IjHrhKgucY",
    "somethin-else": "https://open.spotify.com/album/3Wu0chxAm4GxSeRnIIf2Om",
    "empyrean-isles": "https://open.spotify.com/album/11TXHm0xqob0K697Fz8cSo",
    "jazz-at-massey-hall": "https://open.spotify.com/album/1OTHRJRehmPtgAtBHB8Dqt",
    "blues-and-roots": "https://open.spotify.com/album/7EOQggjtK8JCqeRz9IG33e",
    "heavy-weather": "https://open.spotify.com/album/2M9F2yYsUvqiBPwUGeNvn1",
    "return-to-forever": "https://open.spotify.com/album/6M0IAJHwQ6dFNtTkFsXCJc",
    "in-a-silent-way": "https://open.spotify.com/album/0Hs3BomCdwIWRhgT57x22T",
    "the-koln-concert": "https://open.spotify.com/album/0I8vpSE1bSmysN2PhmHoQg",
    "black-codes": "https://open.spotify.com/album/3yjPy557Rtupp0nxIJ7uZt",
    "juju": "https://open.spotify.com/album/46VoobaZCtFPReElOHFEqq",
    "waltz-for-debby": "https://open.spotify.com/album/3SNo2NOIHpUN6AxIXiaixC",
    "night-dreamer": "https://open.spotify.com/album/2lcz9fPwBhtESyIFVGKvq6",
    "a-night-at-birdland": "https://open.spotify.com/album/6r7judxVxuABrzdTYhNQCr",
    "point-of-departure": "https://open.spotify.com/album/647o8vl4OD1sjvvhql3jFS",
    "blue-note-4000": "https://open.spotify.com/album/6WXQu3KjFlb9Hjwzy3vyS5",
    "unit-structures": "https://open.spotify.com/album/2GQNkSoyBPwTkpuzn8niec",
    "at-fillmore": "https://open.spotify.com/album/4JPRSD7jeZ0lDLONdeERpM",
    "thrust": "https://open.spotify.com/album/00Uf5PRAinCJ0oiCX1Cv2k",
    "bright-size-life": "https://open.spotify.com/album/1wyaHGxXkIGaLGSQTTgKzw",
    "my-song": "https://open.spotify.com/album/6ID17PzjagQlFsc1KFha5v",
    "black-radio": "https://open.spotify.com/album/1yqUCdbw73DpnHBVDwNa3X",
    "esperanza": "https://open.spotify.com/album/7188JsHTl3rladofF7CVvW",
    "the-epic": "https://open.spotify.com/album/2j2q2ySuVk43eHB8wI5XQj",
    "we-insist": "https://open.spotify.com/album/0AFwXU8Y6geV2rxREgKp6a",
    # Batch 2
    "ascension": "https://open.spotify.com/album/2TtadFmrnrFZecasfj0p4t",
    "portrait-in-jazz": "https://open.spotify.com/album/093nLQ4H81HusNsFdGS4Or",
    "study-in-brown": "https://open.spotify.com/album/3158RZskTkHMhPvQICUeQ1",
    "odyssey-of-iska": "https://open.spotify.com/album/21Ui7xabBXaquHWd0ydnGM",
    "straight-no-chaser": "https://open.spotify.com/album/1BHwJqnHhuIryphXMZ0PMQ",
    "monks-dream": "https://open.spotify.com/album/5VTlqV8lZH3YspQ1cDcjrL",
    "at-the-pershing": "https://open.spotify.com/album/3nUwuIFxJid3GQo8c4F6HY",
    "the-bridge": "https://open.spotify.com/album/4IUPjc5q4g3MlRC2TFHHOJ",
    "on-the-corner": "https://open.spotify.com/album/4K7w2LiKZz0CyHXl6OtkOu",
    "extensions": "https://open.spotify.com/album/6ihMlZakvIbQ9U44iHOKbx",
    "search-for-the-new-land": "https://open.spotify.com/album/3SLOCXq3mIgACOJBSScK2D",
    "mercy-mercy-mercy": "https://open.spotify.com/album/6Utj0CAgAWsPLFCVfaqDnB",
    "places-and-spaces": "https://open.spotify.com/album/6btV6MDYhXZ2F6ZKKUfvdh",
    "spectrum": "https://open.spotify.com/album/5JmNk3ayVaujKO5hFvU5YA",
    "birds-of-fire": "https://open.spotify.com/album/6SLknspfGod3v3TyWawl8J",
    "tribal-tech": "https://open.spotify.com/album/66mZKQJyxMfQuI2Bqbg62N",
    "mystic-brew": "https://open.spotify.com/album/2raiYCmtaHV9E2RFtovGfE",
    "blue-in-green": "https://open.spotify.com/album/5MuOxoJbvmGGIQxo6Pudu9",
    "meditations": "https://open.spotify.com/album/0jwbGEDOCydvlWUIhS6gGY",
    "mode-for-joe": "https://open.spotify.com/album/3oqKrOKD60YvIGQ4Xnvxaf",
    "inner-urge": "https://open.spotify.com/album/2Amg9J3U9jEUUJUxCW5OgI",
    "takin-off": "https://open.spotify.com/album/6TylsbZ11vSNjYC4gh0KuY",
    "now-he-sings": "https://open.spotify.com/album/7wKVcBB5SgqVX3Cj3LPllE",
    "in-walked-bud": "https://open.spotify.com/album/3WCsDktjfcjgMivcPnZ6GF",
    "new-york-eye-and-ear": "https://open.spotify.com/album/6cr4HPa9nVsL7WWKXEkchU",
    "spiritual-unity": "https://open.spotify.com/album/5xqgFGNQOl5ilgOu6S1nXg",
    "solo-concerts": "https://open.spotify.com/album/2CMCLp7kOI8Be6rPaYyHeZ",
    "standards-vol-1": "https://open.spotify.com/album/1B99eggrl5BlVvOKknrFTS",
    "buhaina": "https://open.spotify.com/album/2TIaMc9BeIm2j6pq8jVsPJ",
    "caravan": "https://open.spotify.com/album/4AMH2A87ejSK42B7snBJvw",
    "live-at-the-lighthouse": "https://open.spotify.com/album/62r4UbMeVkISnWjWO0xprJ",
    "eastern-sounds": "https://open.spotify.com/album/651p7rfPaB7IiGIIR6Ys7f",
    "idle-moments": "https://open.spotify.com/album/1lDtUlOPGKp56gQ24MvmNG",
    "hub-tones": "https://open.spotify.com/album/6WXQu3KjFlb9Hjwzy3vyS5",
    "red-clay": "https://open.spotify.com/album/2jWaNubVicbGt8kf4NiSqT",
    "space-is-the-place": "https://open.spotify.com/album/4KsD7TdYrEd1NX0q5GMHNt",
    "lanquidity": "https://open.spotify.com/album/4UoSzYIJjNTHgq5gMd84Gw",
    "karma": "https://open.spotify.com/album/04sSPjO9MQFQ6fG4lpBI3G",
    "jewels-of-thought": "https://open.spotify.com/album/4eqjbUVRGuA1iM9Gt1UhaV",
    "black-fire": "https://open.spotify.com/album/2XOQztLkohDDWZH8DEECkQ",
    "judgment": "https://open.spotify.com/album/7mOhgWiuMoAkCAqEtD19Dy",
    "total-eclipse": "https://open.spotify.com/album/22CAQduBWiDnEMAF05wWlM",
    "destination-out": "https://open.spotify.com/album/5G3L2XFdPWxKmsFSljLjj1",
    "one-step-beyond": "https://open.spotify.com/album/5coo4uFLalJIkD6QOyfnlO",
    "evolution": "https://open.spotify.com/album/4lybhjIqqPtLb5xV8sXg3x",
    "some-other-stuff": "https://open.spotify.com/album/2XPmJPxW3ehIa5MfCo5Sv7",
    "fuchsia-swing-song": "https://open.spotify.com/album/0tsowrhCb9ezNEbhG7Xy0W",
    "contours": "https://open.spotify.com/album/4Qk5Ifnki13u4bSvNwXM8Y",
    # Batch 3
    "complete-communion": "https://open.spotify.com/album/21lGaSTCDDxBizt3v2n7hV",
    "fire-music": "https://open.spotify.com/album/1vz97Cr9Jw5A4tJnA7dLNk",
    "mama-too-tight": "https://open.spotify.com/album/3qr5zSyMn6r7chKsSMZRag",
    "the-magic-of-juju": "https://open.spotify.com/album/6lNAzoeQjlcJduquuA9BNt",
    "machine-gun": "https://open.spotify.com/album/0fwlNodwJFh7FB3BVl6ifh",
    "nice-guys": "https://open.spotify.com/album/03Breb0jIGDNVcVsDnnvJv",
    "the-real-mccoy": "https://open.spotify.com/album/22HoIP0ai6Wikh4R8yM0AX",
    "sahara": "https://open.spotify.com/album/0njsEE2XyDZFPXUWiMNrBl",
    "our-man-in-paris": "https://open.spotify.com/album/1igojJAXxPgAUkA0JGjFUE",
    "go": "https://open.spotify.com/album/5nEJj9bjoarnzlS88NiWet",
    "capra-black": "https://open.spotify.com/album/6FzoGnBlKsDqlKa4xdzqdZ",
    "music-matador": "https://open.spotify.com/album/5eubtUqOh4fqfaZXA8Ha4X",
    "street-of-dreams": "https://open.spotify.com/album/43UCKQPN2pDxnqmrI8XxGR",
    "super-nova": "https://open.spotify.com/album/0ilO7avgQcUxwYhgJkZRsU",
    "kulu-se-mama": "https://open.spotify.com/album/58prqRgtdMtOi5ztZnjJya",
    "the-olatunji-concert": "https://open.spotify.com/album/0iaXHEeLgrKOsyNdhIHoE2",
    "live-at-the-five-spot": "https://open.spotify.com/album/2QmssU0RNrWDa0YIJwDcb7",
    "far-cry": "https://open.spotify.com/album/1FTIJYaIRbesBQWL9quJz8",
    "black-woman": "https://open.spotify.com/album/3xWs9FMTAGdQtgwZTnTf98",
    "conference-of-the-birds": "https://open.spotify.com/album/5P0yqYv3GZWsvmIgZNmxAX",
    "jaco-pastorius": "https://open.spotify.com/album/47nWcb5GzhgGNzJuCJgiPN",
    "word-of-mouth": "https://open.spotify.com/album/67QMF9QFjulgts128Z2s2W",
    "looking-ahead": "https://open.spotify.com/album/4cDpOMQWrPPZoSxOIKEAiZ",
    "silent-tongues": "https://open.spotify.com/album/35L84eBzSSJH4i3o38cVhh",
    "journey-in-satchidananda": "https://open.spotify.com/album/6zV55F6W8kh1qe8LHhqRbz",
    "ptah-the-el-daoud": "https://open.spotify.com/album/6XyhwP7a50E4u83H9aM8sD",
    "universal-consciousness": "https://open.spotify.com/album/2YlrEXJnxx7q1wX8sVXIuV",
    "zodiac-suite": "https://open.spotify.com/album/0rNgP6dA7elgUCINGUUeyI",
    "black-christ-of-the-andes": "https://open.spotify.com/album/35TchegKRAVtmhwSfDA8hy",
    "abbey-is-blue": "https://open.spotify.com/album/6fttEitwFXTGtUhlHd0dlp",
    "straight-ahead": "https://open.spotify.com/album/0Xb56bNcIToAFH7VCRtTKK",
    "escalator-over-the-hill": "https://open.spotify.com/album/4Gkvfrv2hZlF1ILyiqVe9j",
    "dinner-music": "https://open.spotify.com/album/2mnNMjyJEwg3sosMz5IcwQ",
    "social-studies": "https://open.spotify.com/album/6YgIHQAp0or3kvqoxsd1sf",
    "betty-carter-album": "https://open.spotify.com/album/19sY1QgcDOQLe8MpHOfYTx",
    "look-what-i-got": "https://open.spotify.com/album/44rPYqxdq5u8XfxY5cwDAl",
    "afro-harping": "https://open.spotify.com/album/1XEPKavl3nlI2qVt8HuA5n",
    "geri-allen-trio": "https://open.spotify.com/album/3W6OYHO3sMLBTcZ63fiApJ",
    "twylight": "https://open.spotify.com/album/6xb4dNbhX5KD0C9U9o9ZZx",
    "nina-at-town-hall": "https://open.spotify.com/album/23Bd6VeIIzJlQ6HfM1eVNg",
    "pastel-blues": "https://open.spotify.com/album/31pd81sWDaK2pP3ok5892z",
    "shirley-scott-trio": "https://open.spotify.com/album/4bI8D1jZ8ZIN4tGbC7fXFf",
    "sarah-vaughan-clifford-brown": "https://open.spotify.com/album/2hIK0XQq04rkz8Bzs2gxho",
    "sassy-swings-the-tivoli": "https://open.spotify.com/album/352XlvQQBk6bJgBNQ2ZmVl",
    "blue-light-til-dawn": "https://open.spotify.com/album/2v88xdHZnM2rHMqBBNRrcA",
    "new-moon-daughter": "https://open.spotify.com/album/7jV22JIrWgtCKCX34cJrzA",
    "here-today-tomorrow": "https://open.spotify.com/album/3FmcKw3HTGQFJD5TGx9h47",
    "close-enough": "https://open.spotify.com/album/57qE8dgdUjxZHkcN2ArH2n",
    "terri-lyne-carrington": "https://open.spotify.com/album/04Qp7yrcgEMRyQ8Z4RDVhP",
    # Batch 4
    "modern-sounds": "https://open.spotify.com/album/5GJ5gYx2VulbjhOuPwlH0A",
    "great-american-songbook": "https://open.spotify.com/album/01LjoVd39soQ63i3NKQiZO",
    "django": "https://open.spotify.com/album/3bMdsH6llaI2OTGulHDYEK",
    "saxophone-supremacy": "https://open.spotify.com/album/0I6SVvkDYGLHSsx1JsVCCq",
    "officium": "https://open.spotify.com/album/6EZ4ZARjmbOF8M9yRzxMxE",
    "facing-you": "https://open.spotify.com/album/2IJMiFlEXfzFqGgotYpB5p",
    "gateway": "https://open.spotify.com/album/17BiOpPnez7L0w8r0yRp9Y",
    "belonging": "https://open.spotify.com/album/6dmq2NJgWAvrzRVrpPwkzv",
    "jazz-in-africa": "https://open.spotify.com/album/6OaQfUg3WKoDDigKggcA3g",
    "township-jive": "https://open.spotify.com/album/5bhs8aeCmPGCPJW48DAjCB",
    "mannenberg": "https://open.spotify.com/album/211IJ33ehIcOM2fdMCxJRp",
    "african-marketplace": "https://open.spotify.com/album/0zP3KrlHyNoOEm7709KOde",
    "grazin-in-the-grass": "https://open.spotify.com/album/21YlyIf7r7nQGypMvogt2D",
    "inhlupeko": "https://open.spotify.com/album/7cSZwj3u1FR4AQqI3ANO5r",
    "afrodisia": "https://open.spotify.com/album/4zVSolem7qvt6njlVAOXMz",
    "shakti": "https://open.spotify.com/album/1Yub41uoYXCmT10jjaEYiz",
    "codona": "https://open.spotify.com/album/05Bmxa8ELUuRcDm5YQA8Hj",
    "azimuth": "https://open.spotify.com/album/5hYUAA48VS6s04b5XA9wjc",
    "witchi-tai-to": "https://open.spotify.com/album/6rzLRyi0TSGxFIGaBPYE9d",
    "gnu-high": "https://open.spotify.com/album/2Mxcgzd05f3MPtu6FLhRvK",
    "saudades": "https://open.spotify.com/album/25XR56bF8zm09Tl3HdItwJ",
    "tauhid": "https://open.spotify.com/album/4RTqDJ4oYVxpgd8Hbt73Bt",
    "thembi": "https://open.spotify.com/album/4Dz5vD2zfKr8OVtIgpcWOy",
    "spirits-known-and-unknown": "https://open.spotify.com/album/5dNECos34GCrknaAo29DyK",
    "world-galaxy": "https://open.spotify.com/album/4vJH84ddOAuXvRhtS0ePex",
    "power-to-the-people": "https://open.spotify.com/album/6vRHnMHYYJkBX5GMRrCLr",
    "celebration-mseleku": "https://open.spotify.com/album/2OFQgGsXO2ZpcUkGyaQ37y",
    "zimology": "https://open.spotify.com/album/5Fi1jbxQ29INXpFGvz3zxh",
    "scenery-ryo-fukui": "https://open.spotify.com/album/5Uny0mkKiVGDat7H6SNDyS",
    "pimp-master": "https://open.spotify.com/album/7fiBdfQjkDrYoGOwK0SEBT",
    "funky-stuff": "https://open.spotify.com/album/6XJZInF8Eg8hLBGNKTeHEI",
    "rising-son": "https://open.spotify.com/album/7GDnn7XSLCIjZkBkw0SMZd",
    "globe-unity": "https://open.spotify.com/album/5CzlvKoaR0rFWQ4bn8l7e7",
    "no-room-for-squares": "https://open.spotify.com/album/3qer0IWDm6mSLUJy4ji0Oi",
    "a-caddy-for-daddy": "https://open.spotify.com/album/1YhqCshhUkaBZvRA1l1tcS",
    "dippin": "https://open.spotify.com/album/3mx9Te2p8koxBI9oe1341j",
    "let-freedom-ring": "https://open.spotify.com/album/7GfDutks6MtlOJA7JFRe45",
    "happenings": "https://open.spotify.com/album/4TbWPn2fJUrQc924iTylFi",
    "back-at-the-chicken-shack": "https://open.spotify.com/album/6YhvR14clg0yibdTKB5aBv",
    # Batch 5
    "face-to-face": "https://open.spotify.com/album/5eaTwFVFo3DLYwcD7cHCPu",
    "the-honeydripper": "https://open.spotify.com/album/4LHoUJ5iUih3y90sObj165",
    "alligator-bogaloo": "https://open.spotify.com/album/4XBcW9JiDXOxXb9sfI1CiX",
    "alive-grant-green": "https://open.spotify.com/album/3X95X0BWAbmflHbXmtkBmu",
    "air-song": "https://open.spotify.com/album/00mZuHtkpXveKBgrP8Cuxn",
    "coin-coin-chapter-two": "https://open.spotify.com/album/5JyneVTGEZzNfSWnkKevv6",
    "amaryllis-belladonna": "https://open.spotify.com/album/5f4X6JHWWACcVWstI7KQUD",
    "mandorla-awakening-ii": "https://open.spotify.com/album/6fzBH8keSx6V6JgdZXLKVE",
    "on-the-tender-spot": "https://open.spotify.com/album/6PTSXZ3c5ZsZzmYUD749ji",
    "slaves-mass": "https://open.spotify.com/album/55yVwJbFIy1OrBBhdCTssq",
    "danca-das-cabecas": "https://open.spotify.com/album/0m4IfvtQuzC1tRFHYuzXuI",
    "open-your-eyes-you-can-fly": "https://open.spotify.com/album/3tj4WEvfmzE4U3Y2tjaynS",
    "expansions": "https://open.spotify.com/album/7p96a8I3q2MRN5Ely3WiVm",
    "blacks-and-blues": "https://open.spotify.com/album/1zCeavwN7ZhPIGR5phKxJv",
    "black-byrd": "https://open.spotify.com/album/0j5Nx6IeRw3H5gohShC0qZ",
    "sound-roscoe-mitchell": "https://open.spotify.com/album/2PWrWz8WH6fNokAkT4Ssk0",
    "levels-and-degrees-of-light": "https://open.spotify.com/album/63uPaLqCKPqNJgPOS1nd0d",
    "for-alto": "https://open.spotify.com/album/5cZjM0N9SoWsieFsJQ1AWH",
    "free-at-last-waldron": "https://open.spotify.com/album/7cRm4SUgrv7ejABJsLFy98",
    "eastern-rebellion": "https://open.spotify.com/album/6Kba7TzUkBLvGJNf0Ycl96",
    "concierto-jim-hall": "https://open.spotify.com/album/104g5VLtuvctk0lxXHokNy",
    "el-hombre": "https://open.spotify.com/album/38YKMgp3B7JKlSUXtSBpVa",
    "ask-the-ages": "https://open.spotify.com/album/0Fx1VWICKcxrZqHJp2l8Jw",
    "tales-of-captain-black": "https://open.spotify.com/album/1pcGyWegydCqFCU5bZhtxA",
    "harlem-river-drive": "https://open.spotify.com/album/5xS4yAQdZc08wecbmy32jV",
    "soul-sauce": "https://open.spotify.com/album/1F3ZdAeTsfMzczAZnbwvUC",
    "the-newest-sound-around": "https://open.spotify.com/album/616qGb6fPngIb7pUVe9tbK",
    "experience-and-judgment": "https://open.spotify.com/album/2sKLuKBYjri0alci8s8rhE",
    "mexican-green": "https://open.spotify.com/album/4I1v2LP8xt9RpfL0NeFnp4",
    "free-form-harriott": "https://open.spotify.com/album/48o6mUuPml1OpzGh88pg6Z",
    "your-queen-is-a-reptile": "https://open.spotify.com/album/4pxnDGBdoGu88h8ZInX5f5",
    "war-orphans": "https://open.spotify.com/album/0vFPcvzSwDcyRueMX0pftk",
    "soul-of-things": "https://open.spotify.com/album/2XFGnloG7wSlHM6pZaUdY1",
    "liberation-music-orchestra": "https://open.spotify.com/album/7rqdziyEA9441OtWILhVwt",
    "emerald-tears": "https://open.spotify.com/album/60pQ02DvHpC2YYyDgJULgR",
    "infernal-machines": "https://open.spotify.com/album/00XtL1ISA7cIgZOWk9CAFA",
    "lenox-avenue-breakdown": "https://open.spotify.com/album/0TjCtBbEIcqcRajdG0oro7",
    "in-the-tradition": "https://open.spotify.com/album/0RGfyiDQK02skZBKTKqOaM",
    "dogon-ad": "https://open.spotify.com/album/5gErsjcIRixZjtcoxK8dnO",
    "revue-wsq": "https://open.spotify.com/album/0iuALmsmjf9zMAGaNlrPrI",
    "the-centaur-and-the-phoenix": "https://open.spotify.com/album/3HHC0WIVnvM6MafAQjmHIX",
    "midnight-blue": "https://open.spotify.com/album/4e6P6Gyvd3FMoYQdFKC6x7",
    "indo-jazz-suite": "https://open.spotify.com/album/2t3N4NoSEEbXD2YNMaW2HD",
    "paths-prints": "https://open.spotify.com/album/29GWURtYGIvRp4b2ofVwm2",
    # Additional from MusicBrainz
    "congo-square": None,
}

# YouTube links from search agents (5 batches)
youtube = {
    # Batch 1
    "hot-fives-sevens": "https://www.youtube.com/watch?v=MrIlWqbHcgE",
    "ellington-at-newport": "https://www.youtube.com/watch?v=9Lg9JP9oYCs",
    "kind-of-blue": "https://www.youtube.com/watch?v=vDqULFUg6CY",
    "a-love-supreme": "https://www.youtube.com/watch?v=ll3CMgiUPuU",
    "blue-train": "https://www.youtube.com/watch?v=UdN38PDzNBs",
    "moanin": "https://www.youtube.com/watch?v=Swz0IfJBtSw",
    "brilliant-corners": "https://www.youtube.com/watch?v=-5OgnlEPzTE",
    "the-shape-of-jazz-to-come": "https://www.youtube.com/watch?v=coFQFk7BDwg",
    "head-hunters": "https://www.youtube.com/watch?v=3m3qOD-hhrQ",
    "maiden-voyage": "https://www.youtube.com/watch?v=l4WWKnGBWIc",
    "time-out": "https://www.youtube.com/watch?v=MSrkU3lEbJQ",
    "bitches-brew": "https://www.youtube.com/watch?v=SbCt-iXIXlQ",
    "birth-of-the-cool": "https://www.youtube.com/watch?v=NvPB3ZyOCrM",
    "mingus-ah-um": "https://www.youtube.com/watch?v=Q97zbRuEkmM",
    "saxophone-colossus": "https://www.youtube.com/watch?v=1BBcGemV9mY",
    "the-black-saint": "https://www.youtube.com/watch?v=hP_vjfC0FlM",
    "speak-no-evil": "https://www.youtube.com/watch?v=wbgsd-Y1mHA",
    "out-to-lunch": "https://www.youtube.com/watch?v=zRekHkcS2X0",
    "sunday-at-the-village-vanguard": "https://www.youtube.com/watch?v=47THBIDYpIw",
    "giant-steps": "https://www.youtube.com/watch?v=xy_fxxj1mMY",
    "money-jungle": "https://www.youtube.com/watch?v=BVdf0F-6pPU",
    "the-sidewinder": "https://www.youtube.com/watch?v=MHCGuBe-mXw",
    "song-for-my-father": "https://www.youtube.com/watch?v=FcgnQxmrsaA",
    "at-carnegie-hall": "https://www.youtube.com/watch?v=dgq_QZ74VI0",
    "free-jazz": "https://www.youtube.com/watch?v=iPDzlSda8P8",
    "chet-baker-sings": "https://www.youtube.com/watch?v=k3LMZ5vxrNc",
    "getz-gilberto": "https://www.youtube.com/watch?v=1QZ5yERcsdM",
    "somethin-else": "https://www.youtube.com/watch?v=mLPW93VIVgs",
    "empyrean-isles": "https://www.youtube.com/watch?v=J2Uf5FkeD3s",
    "jazz-at-massey-hall": "https://www.youtube.com/watch?v=IA_xPya9FMk",
    "blues-and-roots": "https://www.youtube.com/watch?v=aoFNZOHexXs",
    "heavy-weather": "https://www.youtube.com/watch?v=mMsEjdZZSxk",
    "return-to-forever": "https://www.youtube.com/watch?v=zdaRzxP4NuY",
    "in-a-silent-way": "https://www.youtube.com/watch?v=YHesqaMhh34",
    "the-koln-concert": "https://www.youtube.com/watch?v=skkiVoI7sBk",
    "black-codes": "https://www.youtube.com/watch?v=XTx3mNhgqqU",
    "juju": "https://www.youtube.com/watch?v=OzQ9dshXMOM",
    "waltz-for-debby": "https://www.youtube.com/watch?v=mtIp4DPt5lo",
    "night-dreamer": "https://www.youtube.com/watch?v=cE1_b7o0q18",
    "a-night-at-birdland": "https://www.youtube.com/watch?v=9zDl8MliWZE",
    "point-of-departure": "https://www.youtube.com/watch?v=eQdttifZrv4",
    "blue-note-4000": "https://www.youtube.com/watch?v=1fTAIs4qorg",
    "unit-structures": "https://www.youtube.com/watch?v=Y2Tdye6xuGI",
    "at-fillmore": "https://www.youtube.com/watch?v=q_CXQON3CWg",
    "thrust": "https://www.youtube.com/watch?v=ffzjh7nl3Lg",
    "bright-size-life": "https://www.youtube.com/watch?v=iQANdnDFe4c",
    "my-song": "https://www.youtube.com/watch?v=zTIOZb5CoA0",
    "black-radio": "https://www.youtube.com/watch?v=H_hT61-E5kg",
    "esperanza": "https://www.youtube.com/watch?v=0h7jEUbD9K8",
    "the-epic": "https://www.youtube.com/watch?v=g4GCsC_RV5c",
    "we-insist": "https://www.youtube.com/watch?v=SAzTCfZod4c",
    "investigations": "https://www.youtube.com/watch?v=LwIdm4r4VEs",
    # Batch 2
    "ascension": "https://www.youtube.com/watch?v=HRKX-NZTDVI",
    "portrait-in-jazz": "https://www.youtube.com/watch?v=v5eypUpQc7M",
    "study-in-brown": "https://www.youtube.com/watch?v=Ao3bS04RFcs",
    "odyssey-of-iska": "https://www.youtube.com/watch?v=ULYiR8zBQBw",
    "straight-no-chaser": "https://www.youtube.com/watch?v=pYqpecx1XSM",
    "monks-dream": "https://www.youtube.com/watch?v=7cSNNvoJJXQ",
    "at-the-pershing": "https://www.youtube.com/watch?v=6ZOiW7VlBXU",
    "congo-square": "https://www.youtube.com/watch?v=v2VO1XnRfEE",
    "the-bridge": "https://www.youtube.com/watch?v=Vmc1kdCwF-g",
    "on-the-corner": "https://www.youtube.com/watch?v=AIqXprCArdo",
    "extensions": "https://www.youtube.com/watch?v=dkf11L_Qh7c",
    "search-for-the-new-land": "https://www.youtube.com/watch?v=XQIvtqUoekA",
    "mercy-mercy-mercy": "https://www.youtube.com/watch?v=ltGNS9nOvPc",
    "places-and-spaces": "https://www.youtube.com/watch?v=3xszmFo7qi4",
    "spectrum": "https://www.youtube.com/watch?v=gPUHP4VF4cU",
    "birds-of-fire": "https://www.youtube.com/watch?v=RMXaUeciZBo",
    "tribal-tech": "https://www.youtube.com/watch?v=5B7RMxKL6zc",
    "mystic-brew": "https://www.youtube.com/watch?v=kE7DAQv3SwA",
    "blue-in-green": "https://www.youtube.com/watch?v=0M-mQyJ_6Hc",
    "meditations": "https://www.youtube.com/watch?v=TuzfMR-7v1I",
    "mode-for-joe": "https://www.youtube.com/watch?v=WmJ1XMTbLHs",
    "inner-urge": "https://www.youtube.com/watch?v=5ek_cy_2dWA",
    "takin-off": "https://www.youtube.com/watch?v=O1KPrOibtLQ",
    "now-he-sings": "https://www.youtube.com/watch?v=D1m6y-3lySs",
    "in-walked-bud": "https://www.youtube.com/watch?v=tJY5Y9aMRkU",
    "new-york-eye-and-ear": "https://www.youtube.com/watch?v=PXMILAOcH_o",
    "spiritual-unity": "https://www.youtube.com/watch?v=xWsIG5sNq1Q",
    "solo-concerts": "https://www.youtube.com/watch?v=ZZ-MUVG5y60",
    "standards-vol-1": "https://www.youtube.com/watch?v=NHGx_6w-lmU",
    "buhaina": "https://www.youtube.com/watch?v=O7mASYHNwn4",
    "caravan": "https://www.youtube.com/watch?v=pp6d3txPKvw",
    "live-at-the-lighthouse": "https://www.youtube.com/watch?v=1mQ7dIV-3xE",
    "eastern-sounds": "https://www.youtube.com/watch?v=YMTHsK3MlzA",
    "idle-moments": "https://www.youtube.com/watch?v=QKAUl-eGsLA",
    "hub-tones": "https://www.youtube.com/watch?v=Bee0aqfSRFA",
    "red-clay": "https://www.youtube.com/watch?v=D0BrQ0h9aPc",
    "space-is-the-place": "https://www.youtube.com/watch?v=SVCzaxmM1G4",
    "lanquidity": "https://www.youtube.com/watch?v=238Dh6N9GLg",
    "karma": "https://www.youtube.com/watch?v=2t88stnbP0g",
    "jewels-of-thought": "https://www.youtube.com/watch?v=fBzQP6QprBI",
    "black-fire": "https://www.youtube.com/watch?v=mSwhHSlOoBc",
    "judgment": "https://www.youtube.com/watch?v=01EwcflVvg0",
    "total-eclipse": "https://www.youtube.com/watch?v=pNVdsYwIBaQ",
    "destination-out": "https://www.youtube.com/watch?v=qXuZIhn6vP4",
    "one-step-beyond": "https://www.youtube.com/watch?v=iaDgO2KaasQ",
    "evolution": "https://www.youtube.com/watch?v=5hIqmji2wlY",
    "some-other-stuff": "https://www.youtube.com/watch?v=3kWet8qK5NA",
    "fuchsia-swing-song": "https://www.youtube.com/watch?v=pcnQSA4e8Do",
    "contours": "https://www.youtube.com/watch?v=00zLwZJ2SG0",
    # Batch 3
    "complete-communion": "https://www.youtube.com/watch?v=9RUGa4gggmg",
    "fire-music": "https://www.youtube.com/watch?v=5Yi552zRJb4",
    "mama-too-tight": "https://www.youtube.com/watch?v=Jkg_fO9fhpk",
    "the-magic-of-juju": "https://www.youtube.com/watch?v=zeOdqw7rbNc",
    "machine-gun": "https://www.youtube.com/watch?v=iaifuU1JcEA",
    "nice-guys": "https://www.youtube.com/watch?v=BoP0-UImSH0",
    "les-stances-a-sophie": "https://www.youtube.com/watch?v=JmN9rkVfsmo",
    "the-real-mccoy": "https://www.youtube.com/watch?v=P5Y0sBc3WYE",
    "sahara": "https://www.youtube.com/watch?v=wIrXpZHgiCQ",
    "our-man-in-paris": "https://www.youtube.com/watch?v=pWy7UiFe4Us",
    "go": "https://www.youtube.com/watch?v=znb4-Uc8i8k",
    "capra-black": "https://www.youtube.com/watch?v=NLebPLl7fc4",
    "music-matador": "https://www.youtube.com/watch?v=pJJ2Jcp-vUU",
    "street-of-dreams": "https://www.youtube.com/watch?v=08balpAm9Ak",
    "super-nova": "https://www.youtube.com/watch?v=4qhJlwC76og",
    "kulu-se-mama": "https://www.youtube.com/watch?v=g1X1ftz5SMg",
    "the-olatunji-concert": "https://www.youtube.com/watch?v=6cR8Ic3F5eM",
    "live-at-the-five-spot": "https://www.youtube.com/watch?v=HlWCUN2EdNc",
    "far-cry": "https://www.youtube.com/watch?v=SUFT6xWj3ow",
    "black-woman": "https://www.youtube.com/watch?v=w38o2dJI_cQ",
    "conference-of-the-birds": "https://www.youtube.com/watch?v=_ALPmRk3Ht4",
    "jaco-pastorius": "https://www.youtube.com/watch?v=Zkx6C4LEzWE",
    "word-of-mouth": "https://www.youtube.com/watch?v=OVekAwFrik0",
    "looking-ahead": "https://www.youtube.com/watch?v=ZcsR8VDxIiE",
    "silent-tongues": "https://www.youtube.com/watch?v=W0T9KvgS4yQ",
    "journey-in-satchidananda": "https://www.youtube.com/watch?v=NxPMKgY_8qk",
    "ptah-the-el-daoud": "https://www.youtube.com/watch?v=BiMHewopOAY",
    "universal-consciousness": "https://www.youtube.com/watch?v=kxn3tCO7Q_8",
    "zodiac-suite": "https://www.youtube.com/watch?v=mBPepNvOzQw",
    "black-christ-of-the-andes": "https://www.youtube.com/watch?v=6kRT9M8h3JE",
    "abbey-is-blue": "https://www.youtube.com/watch?v=c8NwxTpJjto",
    "straight-ahead": "https://www.youtube.com/watch?v=B60tL9LdnbM",
    "escalator-over-the-hill": "https://www.youtube.com/watch?v=LB90soiyAsA",
    "dinner-music": "https://www.youtube.com/watch?v=3i2-BMTx3Vo",
    "social-studies": "https://www.youtube.com/watch?v=aLYA3jvobLk",
    "betty-carter-album": "https://www.youtube.com/watch?v=RD7V7xTL0QE",
    "look-what-i-got": "https://www.youtube.com/watch?v=JQZDuohot48",
    "afro-harping": "https://www.youtube.com/watch?v=Ojuz4XlxKmM",
    "geri-allen-trio": "https://www.youtube.com/watch?v=GUyYENuitPg",
    "twylight": "https://www.youtube.com/watch?v=MucG24HZgPo",
    "nina-at-town-hall": "https://www.youtube.com/watch?v=_3S-kCd5h4U",
    "pastel-blues": "https://www.youtube.com/watch?v=AbisPR1JpqU",
    "blue-flames": "https://www.youtube.com/watch?v=CuqPKhuS7hQ",
    "sarah-vaughan-clifford-brown": "https://www.youtube.com/watch?v=fVsSIVL2qog",
    "sassy-swings-the-tivoli": "https://www.youtube.com/watch?v=yrPeXlhAXbk",
    "blue-light-til-dawn": "https://www.youtube.com/watch?v=aIjw9k0ykLc",
    "new-moon-daughter": "https://www.youtube.com/watch?v=YHbcwby7igA",
    "here-today-tomorrow": "https://www.youtube.com/watch?v=UTv3TONfTTQ",
    "close-enough": "https://www.youtube.com/watch?v=362K3rLvjxc",
    "terri-lyne-carrington": "https://www.youtube.com/watch?v=zRhG6RwLpEU",
    # Batch 4
    "modern-sounds": "https://www.youtube.com/watch?v=PZwsJeU2_ik",
    "great-american-songbook": "https://www.youtube.com/watch?v=O0vdCOvJSc0",
    "django": "https://www.youtube.com/watch?v=lOt_v67Fj4o",
    "saxophone-supremacy": "https://www.youtube.com/watch?v=JtfFdoangIc",
    "officium": "https://www.youtube.com/watch?v=jBPbLKcJ94Q",
    "facing-you": "https://www.youtube.com/watch?v=hRKM5mrUs3M",
    "gateway": "https://www.youtube.com/watch?v=NLOA5mlho7A",
    "belonging": "https://www.youtube.com/watch?v=Pz2GaiIVUw8",
    "kosmos": "https://www.youtube.com/watch?v=-XYpMDjSgJQ",
    "sadao-watanabe-mbali": "https://www.youtube.com/watch?v=kSNBXPKinz4",
    "jazz-in-africa": "https://www.youtube.com/watch?v=KNMvy9oOXGQ",
    "blue-notes-legacy": "https://www.youtube.com/watch?v=u1lWpLFGhjE",
    "township-jive": "https://www.youtube.com/watch?v=9uoHj_fYb0Y",
    "mannenberg": "https://www.youtube.com/watch?v=5Z79hv5I2Kw",
    "african-marketplace": "https://www.youtube.com/watch?v=tgOhy71noWA",
    "grazin-in-the-grass": "https://www.youtube.com/watch?v=qxXZF60EPdM",
    "inhlupeko": "https://www.youtube.com/watch?v=X7fkP7KFPDQ",
    "afrodisia": "https://www.youtube.com/watch?v=4-pkgVyhIuU",
    "shakti": "https://www.youtube.com/watch?v=Sm8ycb5zjoo",
    "codona": "https://www.youtube.com/watch?v=xteMak5ak68",
    "azimuth": "https://www.youtube.com/watch?v=3GPpfvQOEZg",
    "witchi-tai-to": "https://www.youtube.com/watch?v=KdpzC_VzwQI",
    "gnu-high": "https://www.youtube.com/watch?v=XczCE8jeTP8",
    "saudades": "https://www.youtube.com/watch?v=k_47ifmtu1s",
    "tauhid": "https://www.youtube.com/watch?v=kWBVlfcPXho",
    "thembi": "https://www.youtube.com/watch?v=4Q5dM0mJQVI",
    "spirits-known-and-unknown": "https://www.youtube.com/watch?v=uoYnvw-97II",
    "world-galaxy": "https://www.youtube.com/watch?v=hJyncnM7jZk",
    "power-to-the-people": "https://www.youtube.com/watch?v=WSQA61ENeRc",
    "harlem-bush-music-taifa": "https://www.youtube.com/watch?v=KzlNC_y5XkA",
    "in-the-townships": "https://www.youtube.com/watch?v=a-T1SsaIFUU",
    "spirits-rejoice-moholo": "https://www.youtube.com/watch?v=UgxpQiWDue8",
    "celebration-mseleku": "https://www.youtube.com/watch?v=8NCTjRzYr6U",
    "zimology": "https://www.youtube.com/watch?v=DCijitbXYnA",
    "scenery-ryo-fukui": "https://www.youtube.com/watch?v=Hrr3dp7zRQY",
    "mellow-dream": "https://www.youtube.com/watch?v=KxlvMmUjpTY",
    "funky-stuff": "https://www.youtube.com/watch?v=3Lyv6VPcxa8",
    "rising-son": "https://www.youtube.com/watch?v=ekftatkjrII",
    "globe-unity": "https://www.youtube.com/watch?v=MH_TgVXemLc",
    "saxophone-solos": "https://www.youtube.com/watch?v=ybIZa2xnoEc",
    "solo-guitar-bailey": "https://www.youtube.com/watch?v=2RyMUqjVRE8",
    "tetterettet": "https://www.youtube.com/watch?v=9aNlEXiDkiM",
    "ammmusic": "https://www.youtube.com/watch?v=BwgkBZ-FLW0",
    "no-room-for-squares": "https://www.youtube.com/watch?v=WrkHZfDH0vU",
    "a-caddy-for-daddy": "https://www.youtube.com/watch?v=1iHP3EV94Dk",
    "dippin": "https://www.youtube.com/watch?v=54zXsZNaYj8",
    "let-freedom-ring": "https://www.youtube.com/watch?v=Fvy553GFY64",
    "happenings": "https://www.youtube.com/watch?v=Ej10LP2eodU",
    "back-at-the-chicken-shack": "https://www.youtube.com/watch?v=SuMd8ldLqxo",
    # Batch 5
    "face-to-face": "https://www.youtube.com/watch?v=EYiM62YyvQQ",
    "the-honeydripper": "https://www.youtube.com/watch?v=SXGrJJdCwZk",
    "alligator-bogaloo": "https://www.youtube.com/watch?v=jAFiKJcw5zI",
    "alive-grant-green": "https://www.youtube.com/watch?v=svZX579G0s4",
    "flowers-for-albert": "https://www.youtube.com/watch?v=xZr7g8tJ3yo",
    "air-song": "https://www.youtube.com/watch?v=9kwvUnDC6CI",
    "when-was-that": "https://www.youtube.com/watch?v=S_4hAt5BaXo",
    "the-peoples-republic": "https://www.youtube.com/watch?v=PUFWWuw7qVQ",
    "coin-coin-chapter-two": "https://www.youtube.com/watch?v=rbqk0GNGxRY",
    "inner-spectrum-of-variables": "https://www.youtube.com/watch?v=hphwGTxuGS0",
    "amaryllis-belladonna": "https://www.youtube.com/watch?v=JN7YgG8hsWg",
    "mandorla-awakening-ii": "https://www.youtube.com/watch?v=zP7FRucsNKc",
    "on-the-tender-spot": "https://www.youtube.com/watch?v=Xopajw-oNnE",
    "slaves-mass": "https://www.youtube.com/watch?v=O3q1WNArobw",
    "danca-das-cabecas": "https://www.youtube.com/watch?v=yAV5tJYnDcY",
    "open-your-eyes-you-can-fly": "https://www.youtube.com/watch?v=L-yYZg-DQYQ",
    "expansions": "https://www.youtube.com/watch?v=z0XeKLaqkZs",
    "blacks-and-blues": "https://www.youtube.com/watch?v=sw8D28Z6LwQ",
    "black-byrd": "https://www.youtube.com/watch?v=UeDPRW-SuuA",
    "sound-roscoe-mitchell": "https://www.youtube.com/watch?v=RLq2jx8oSbE",
    "levels-and-degrees-of-light": "https://www.youtube.com/watch?v=TJQhyPpfgbk",
    "for-alto": "https://www.youtube.com/watch?v=ao-lXk2zef0",
    "free-at-last-waldron": "https://www.youtube.com/watch?v=H6itn0MkPHc",
    "eastern-rebellion": "https://www.youtube.com/watch?v=nuYeeMcyCIk",
    "concierto-jim-hall": "https://www.youtube.com/watch?v=VTwb-SJ_qK8",
    "el-hombre": "https://www.youtube.com/watch?v=L8pbMfdSzfQ",
    "ask-the-ages": "https://www.youtube.com/watch?v=S1IGmiHjIyA",
    "tales-of-captain-black": "https://www.youtube.com/watch?v=1Ar6mUOs1BE",
    "harlem-river-drive": "https://www.youtube.com/watch?v=tHYNf1Lg6kA",
    "soul-sauce": "https://www.youtube.com/watch?v=07vqkkRfnnw",
    "the-newest-sound-around": "https://www.youtube.com/watch?v=Mb9q8EswE10",
    "experience-and-judgment": "https://www.youtube.com/watch?v=UFsSXVkdi_I",
    "mexican-green": "https://www.youtube.com/watch?v=5a62j1H8SJI",
    "free-form-harriott": "https://www.youtube.com/watch?v=xPLC5Xf5nWk",
    "your-queen-is-a-reptile": "https://www.youtube.com/watch?v=S00QHjIhDfk",
    "war-orphans": "https://www.youtube.com/watch?v=GC-TxE23Upg",
    "soul-of-things": "https://www.youtube.com/watch?v=0Vw9YRbb0X0",
    "liberation-music-orchestra": "https://www.youtube.com/watch?v=quHy6exgHPI",
    "emerald-tears": "https://www.youtube.com/watch?v=Ph7B876Q0eo",
    "concert-in-the-garden": "https://www.youtube.com/watch?v=j8RQXH2d_xs",
    "infernal-machines": "https://www.youtube.com/watch?v=jfXKmIa1fU8",
    "lenox-avenue-breakdown": "https://www.youtube.com/watch?v=ZWKvf_gX3XM",
    "in-the-tradition": "https://www.youtube.com/watch?v=A7EPsjk_bcg",
    "dogon-ad": "https://www.youtube.com/watch?v=hWkma6Uzc0w",
    "revue-wsq": "https://www.youtube.com/watch?v=OSPJYihT7Uk",
    "the-centaur-and-the-phoenix": "https://www.youtube.com/watch?v=xo1t1PoTelE",
    "midnight-blue": "https://www.youtube.com/watch?v=fZfbROH5U8o",
    "indo-jazz-suite": "https://www.youtube.com/watch?v=U-_uyBwh7FQ",
    "paths-prints": "https://www.youtube.com/watch?v=XqFm3y12bGE",
    "pimp-master": None,
}

# Apply all links
spotify_count = 0
apple_count = 0
youtube_count = 0

for album in albums:
    aid = album['id']

    # Spotify
    if aid in spotify and spotify[aid]:
        if not album.get('spotifyUrl'):
            album['spotifyUrl'] = spotify[aid]
            spotify_count += 1

    # Apple Music
    if aid in apple_music and apple_music[aid]:
        if not album.get('appleMusicUrl'):
            album['appleMusicUrl'] = apple_music[aid]
            apple_count += 1

    # YouTube
    if aid in youtube and youtube[aid]:
        if not album.get('youtubeUrl'):
            album['youtubeUrl'] = youtube[aid]
            youtube_count += 1

# Save
with open(albums_path, 'w') as f:
    json.dump(albums, f, indent=2, ensure_ascii=False)

# Report
total = len(albums)
has_spotify = sum(1 for a in albums if a.get('spotifyUrl'))
has_apple = sum(1 for a in albums if a.get('appleMusicUrl'))
has_youtube = sum(1 for a in albums if a.get('youtubeUrl'))

print(f'Applied: +{spotify_count} Spotify, +{apple_count} Apple Music, +{youtube_count} YouTube')
print(f'\nFinal coverage:')
print(f'  Spotify: {has_spotify}/{total} ({has_spotify*100//total}%)')
print(f'  Apple Music: {has_apple}/{total} ({has_apple*100//total}%)')
print(f'  YouTube: {has_youtube}/{total} ({has_youtube*100//total}%)')

# List missing
no_spotify = [a['id'] for a in albums if not a.get('spotifyUrl')]
no_apple = [a['id'] for a in albums if not a.get('appleMusicUrl')]
no_youtube = [a['id'] for a in albums if not a.get('youtubeUrl')]

if no_spotify:
    print(f'\nMissing Spotify ({len(no_spotify)}): {no_spotify}')
if no_apple:
    print(f'\nMissing Apple Music ({len(no_apple)}): {no_apple}')
if no_youtube:
    print(f'\nMissing YouTube ({len(no_youtube)}): {no_youtube}')
